version: '3'
services:
  todofront:
    image: node:14-alpine
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - "todoback"  
    environment:
      - REACT_APP_API_HOST=todobackend  

  todoback:
    image: node:14-alpine
    restart: always
    ports:
      - 3001:3001
  
  todotests:
    image: mjgargani/puppeteer:trybe1.0
    environment:
      - FRONT_HOST=todofrontend
    depends_on:
      - "todofront"
    restart: always  